# Generated by Django 4.1.6 on 2023-02-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Places',
        ),
    ]
